client/main.js, client/stylesheets/form.scss, package.json, server/app.js, server/modules/form/api.js, server/modules/form/constants.js, server/modules/form/middleware.js, server/modules/marketo/constants.js, test/server/modules/form/api.spec.js, views/error.html, views/exists.html, views/form.html
=> Handle submission errors

Makefile, bower.json, client/components/confirmation.js, client/components/form.js, client/components/utils.js, client/main.js, client/stylesheets/confirmation.scss, package.json, server/app.js, server/modules/cache/service.js, server/modules/content/constants.js, server/modules/content/service.js, server/modules/es/service.js, server/modules/form/api.js, server/modules/form/middleware.js, server/modules/form/router.js, test/server/modules/cache/service.spec.js, test/server/modules/content/service.spec.js, test/server/modules/es/service.spec.js, test/server/modules/form/api.spec.js, views/confirm.html
=> Access Control

server/app.js
=> Fetch serviceworker file from ft.com

server/app.js
=> Set content-type for SW endpoint

server/modules/content/service.js, test/server/modules/content/service.spec.js
=> Set access lifetime to 60 minutes

client/stylesheets/confirmation.scss
=> Add styles for focus states

client/stylesheets/confirmation.scss, views/confirm.html
=> Left align button on mobile

client/components/confirmation.js, client/components/form.js, client/components/submission.js, client/components/utils.js, client/main.js, server/modules/form/api.js, test/server/modules/form/api.spec.js, views/confirm.html
=> Add custom tracking events

server/app.js, test/server/app.spec.js
=> Add not-found handler

server/modules/form/api.js, server/modules/form/middleware.js
=> Add metrics for confirmation events

server/modules/form/middleware.js, server/modules/form/router.js
=> Set latter stage form routes to no-cache

server/modules/form/api.js
=> Remove user links from nav

server/modules/form/api.js
=> Make header logo only

server/modules/form/api.js, server/modules/form/constants.js, server/modules/form/middleware.js, views/form.html
=> Pass marketingName through to marketo

package.json, secret-squirrel.js, server/app.js, server/modules/api/api.js, server/modules/api/middleware.js, server/modules/api/router.js, server/modules/marketo/constants.js, server/modules/marketo/service.js, test/server/modules/api/api.spec.js
=> Create marketo endpoint

server/modules/marketo/constants.js, test/server/modules/api/api.spec.js
=> Add required boolean to Marketo api endpoint

docs/ARCHITECTURE.md, docs/MONITORING.md, docs/TROUBLESHOOTING.md, server/modules/marketo/constants.js, test/server/modules/api/api.spec.js
=> Add docs and rename jobTitle to title

server/modules/api/middleware.js, test/server/modules/api/api.spec.js
=> change api-key to x-api-key

Makefile, package.json
=> bump dependencies

server/app.js
=> hotfix x-frame header

server/modules/marketo/constants.js, test/server/modules/marketo/schema.spec.js
@alexnaish worth you checking this when you are back from xmas
🐿 v2.5.16
=> allow empty strings in payload

test/server/modules/form/api.spec.js, views/form.html
=> Update copy to say 'work phone number'

server/app.js, server/config/health-checks/pingdom.js
=> Add custom pingdom healthcheck

server/modules/form/middleware.js
=> Clean params before use

bower.json, package.json, server/modules/api/middleware.js
=> Fix ombudsman related errors

test/server/modules/form/api.spec.js
See https://github.com/Financial-Times/n-express/pull/484 for reference
🐿 v2.7.0
=> Remove `no-store` check from unit test

server/modules/marketo/constants.js
https://sentry.io/nextftcom/ft-next-corp-signup/issues/525331330/?query=is:unresolved
🐿 v2.8.0
=> Loosen phone input to match form

views/form.html
=> Centering profile form

server/modules/api/api.js
=> add reason to error response

test/server/modules/content/service.spec.js, test/server/modules/es/service.spec.js, test/server/modules/form/api.spec.js, test/server/modules/marketo/service.spec.js, views/confirm.html
=> update sinon syntax

server/modules/form/api.js, server/modules/graph-ql/getUserEmail.js, test/server/modules/marketo/service.spec.js
=> Fix missing session error, remove only, add render log event

.circleci/config.yml
=> Force NPM 5.7 on Circle

server/modules/form/api.js, server/modules/form/router.js, test/server/modules/form/api.spec.js
=> Remove cache headers for form

server/modules/marketo/constants.js
=> Update default Marketo field schema

package.json, server/app.js, server/modules/form/api.js, server/modules/form/middleware.js, server/modules/form/router.js, test/server/modules/form/api.spec.js
https://trello.com/c/Uq08XpxR/635-b2b-link-for-unmasking-form
🐿 v2.10.1
=> New teamtrial theme / URL (unmasking with appshell)

package.json
https://github.com/Financial-Times/next/issues/170
=> Upgrade n-health.

server/modules/form/api.js, server/modules/form/middleware.js, server/modules/marketo/constants.js, views/form.html
=> Send segment ID to Marketo (if present)

server/modules/marketo/constants.js, views/form.html
=> Track spoor ID in spoor Marketo field

client/components/utils.js
=> Add default formType to tracking events

client/components/utils.js
=> update default formtype

.circleci/config.yml, Makefile, app.json, package.json
These changes have been made as part of the Heroku Migration epic, as documented here: https://github.com/Financial-Times/next/wiki/Heroku-review-apps-deployment#miscellaneous
resolves #100
=> ETG Heroku Migration
